#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         8
bspc config window_gap          22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

#Dracula Theme for BSPWM
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

polybar example &
