#! /bin/sh

# bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor HDMI-2 -d 6 7 8 9 10

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         8
bspc config window_gap          22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

#Dracula Theme for BSPWM
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

#polybar example
polybar top
