#!/bin/sh

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

alias config='git --git-dir=/home/beniamino/dotfiles --work-tree=/home/beniamino'
alias grep="grep --color=auto"
alias ls="ls --color=auto"
alias please="sudo"
alias vfz='fzf | xargs -o vim'

